### ISSUE TITLE
Duplicate name in namespace Namespace : ProtoTradeSide

### ISSUE THREAD

**Issue by edgaru** [spotware/connect-nodejs-samples#13]
Tested on nodejs 4 and 6.

``` javascript
Error: Duplicate name in namespace Namespace : ProtoTradeSide
    at Error (native)
    at ProtoBuf.Reflect.NamespacePrototype.addChild (/root/connect-nodejs-samples/node_modules/protobufjs/dist/protobuf.js:1561:27)
    at ProtoBuf.Builder.BuilderPrototype.create (/root/connect-nodejs-samples/node_modules/protobufjs/dist/protobuf.js:4527:34)
    at ProtoBuf.Builder.BuilderPrototype.import (/root/connect-nodejs-samples/node_modules/protobufjs/dist/protobuf.js:4720:22)
    at ProtoBuf.Builder.BuilderPrototype.import (/root/connect-nodejs-samples/node_modules/protobufjs/dist/protobuf.js:4692:43)
    at Object.ProtoBuf.loadJson (/root/connect-nodejs-samples/node_modules/protobufjs/dist/protobuf.js:5183:26)
    at Object.ProtoBuf.loadProto (/root/connect-nodejs-samples/node_modules/protobufjs/dist/protobuf.js:5086:25)
    at Object.ProtoBuf.loadProtoFile (/root/connect-nodejs-samples/node_modules/protobufjs/dist/protobuf.js:5132:52)
    at null.<anonymous> (/root/connect-nodejs-samples/node_modules/connect-protobuf-messages/index.js:45:33)
    at Array.map (native)
```

**Comment by spirinvladimir** [comment]
Hi @edgaru, thanks for the issue. I also have same problem. I've found the reason of this problem and fix it with PR #14 .
